# Generated by Django 3.2.18 on 2023-04-07 12:24

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_num', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
                ('date_booked', models.DateTimeField()),
                ('time_booked', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=55, unique=True)),
                ('email', models.EmailField(max_length=55)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IE', unique=True)),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField()),
                ('num_of_people', models.IntegerField()),
                ('table_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking_system.table')),
            ],
        ),
    ]
