# Generated by Django 3.2.18 on 2023-04-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='date_booked',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='time_booked',
            field=models.TimeField(),
        ),
    ]
