# Generated by Django 3.2.18 on 2023-04-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0002_auto_20230407_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='date_booked',
        ),
        migrations.RemoveField(
            model_name='table',
            name='time_booked',
        ),
    ]
