# Generated by Django 3.2.18 on 2023-05-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0005_auto_20230509_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='fullname',
            new_name='name',
        ),
    ]
